language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jpbodiong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jpbodiong/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-001991640692"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"