language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jpbodiong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jpbodiong/docker-react npm run test